### PR TITLE
Fix loading of sockethub-client library

### PR DESCRIPTION
**Pull request by galfert**
Dependencies are installed directly in node_modules of the main app instead of as a subdirectory of the depending library now.

So there is no need to add the `node_modules` subdirectory to the Broccoli tree anymore.

### CODE REVIEW

**Comment by skddc** [comment]
Can we specify a minimum npm version (the one with the npm-dep level change) for this in package.json?

**Comment by galfert** [comment]
Looks like you could define it in the `engines` field. See https://docs.npmjs.com/files/package.json#engines.

Any idea which version introduced the new directory structure?

**Comment by skddc** [comment]
Looks like it was introduced in major version 3: https://docs.npmjs.com/how-npm-works/npm3

**Comment by skddc** [comment]
Note that it still installs nested dependencies, when various modules depend on different versions. It'll install whatever it encounters first on the first level and all subsequently found versions within the respective module folders.

> However, since B v1.0 is already a top-level dep, we cannot install B v2.0 as a top level dependency. npm v3 handles this by defaulting to npm v2 behavior and nesting the new, different, module B version dependency under the module that requires it -- in this case, module C.

This shouldn't concern us, as only `ember-cli-sockethub` should require `sockethub-client`, but it's useful to keep this in mind in the future I think.

**Comment by skddc** [comment]
Tested locally and works.

I added a minimum requirement for npm3. Plz review again and merge if ok.

**Comment by galfert** [comment]
Cool, thanks.

**Pull request merged**
